# Generated by Django 5.2 on 2025-04-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='patients',
            new_name='patient',
        ),
    ]
